### ISSUE TITLE
Do you have any example of authentication using websocket?

### ISSUE THREAD

**Issue by Gushono** [y-crdt/ypy-websocket#29]
I would like to know if you have any examples of ypy-websocket being used in an API.

**Comment by davidbrochart** [comment]
You can find an example using Tornado [here](https://github.com/jupyter-server/jupyter_server_ydoc/blob/d175b8a607985886ef0fd51af994ae186b527c12/jupyter_server_ydoc/ydoc.py#L73-L77), and using FastAPI [here](https://github.com/jupyter-server/jupyverse/blob/0fa8e399e013c13b4a30ee0cec2814fd084c950a/plugins/yjs/fps_yjs/routes.py#L44-L67).

**Comment by davidbrochart** [comment]
I don't have a full example, but you should look at the `WebsocketProvider`, as it can be used as a building block for a collaborative editor using Python.
