### ISSUE TITLE
ASGI compatible server

### ISSUE THREAD

**Issue by rmorshea** [y-crdt/ypy-websocket#37]
This would be more useful if the server were compatible with the [ASGI spec](https://asgi.readthedocs.io/en/latest/). If it were, ypy-websocket could immediately be used in conjunction with popular web servers like [Starlette](https://www.starlette.io/), [FastAPI](https://fastapi.tiangolo.com/), and [Sanic](https://sanic.readthedocs.io/en/stable/).

**Comment by davidbrochart** [comment]
I agree, on the other hand ypy-websocket is used in [Jupyter Server](https://github.com/jupyter-server/jupyter_server_ydoc), which still uses Tornado, but there could probably be an adapter to make it work there.
Do you want to take a stab at it? Your contribution would be greatly appreciated!

**Comment by rmorshea** [comment]
It would probably be some time before I get to it, but yes, when I get around to https://github.com/idom-team/idom/issues/826 I'd start work on this.

**Comment by linspw** [comment]
Hello everything is fine?
This ASGI support would help a lot, I'm trying to use this lib somehow in conjunction with django channels.
If it had the implementation in ASGI it would help a lot.

I would like to contribute, but I have no idea how to create an adapter in this sense.

**Comment by davidbrochart** [comment]
Hi @linspw,
I've not looked at it yet, but feel free to contribute. Maybe @rmorshea has ideas?

**Comment by rmorshea** [comment]
I don't think I'm going to get to this any time soon.

**Comment by davidbrochart** [comment]
I'm not very familiar with ASGI, does anyone know if this would have to be implemented from scratch or if it would be better to use e.g. [Starlette](https://www.starlette.io/websockets)?
