### ISSUE TITLE
Changelog and release process

### ISSUE THREAD

**Issue by davidbrochart** [y-crdt/ypy-websocket#46]
We need to start documenting changes. This is not a Jupyter project, but it could be nice to use [jupyter-releaser](https://github.com/jupyter-server/jupyter_releaser).
What do you think?

**Comment by davidbrochart** [comment]
It looks like I didn't push the bump of the version to `0.7.1` upstream, but the PyPI package is fine for v0.7.1.
Another reason to switch to Jupyter Releaser.

**Comment by jtpio** [comment]
+1 for using the releaser :+1:
