### ISSUE TITLE
aiofiles version limit

### ISSUE THREAD

**Issue by frenzymadness** [y-crdt/ypy-websocket#66]
It seems to me that this package works fine with aiofiles 23 so the upper version limit can be higher or removed.

https://github.com/y-crdt/ypy-websocket/blob/0ae0a17ff096051563c4dc2087b950be9795d6f7/pyproject.toml#L19

**Comment by squeezer44** [comment]
I just received an error message (dependency conflict) as I upgraded the module  aiofiles 23.1.0:

`ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
ypy-websocket 0.8.4 requires aiofiles<23,>=22.1.0, but you have aiofiles 23.1.0 which is incompatible.`

So good to hear: this package works fine with aiofiles 23

**Comment by davidbrochart** [comment]
I think we should use [AnyIO](https://anyio.readthedocs.io/en/stable/fileio.html) instead of [aiofiles](https://github.com/Tinche/aiofiles).
