### ISSUE TITLE
Usage example fails with exception

### ISSUE THREAD

**Issue by cschuet** [y-crdt/ypy-websocket#67]
Hi,

Thanks for all the great work on making CRDTs generally accessible to developers.

I tried the examples snippets for client and server in the README.md but the client fails with an exception.

server.py
```
import asyncio
from websockets import serve
from ypy_websocket import WebsocketServer

async def server():
    websocket_server = WebsocketServer()
    async with serve(websocket_server.serve, "localhost", 1234):
        await asyncio.Future()  # run forever

asyncio.run(server())
```

client.py
```
import asyncio
import y_py as Y
from websockets import connect
from ypy_websocket import WebsocketProvider

async def client():
    ydoc = Y.YDoc()
    async with connect("ws://localhost:1234/my-roomname") as websocket:
        WebsocketProvider(ydoc, websocket)
        ymap = ydoc.get_map("map")
        with ydoc.begin_transaction() as t:
            ymap.set(t, "key", "value")

asyncio.run(client())
```

fails with
```
Task exception was never retrieved
future: <Task finished coro=<WebsocketProvider._run() done, defined at /home/chris/.local/lib/python3.7/site-packages/ypy_websocket/websocket_provider.py:29> exception=ConnectionClosedOK(Close(code=1000, reason=''), Close(code=1000, reason=''), False)>
Traceback (most recent call last):
  File "/home/chris/.local/lib/python3.7/site-packages/ypy_websocket/websocket_provider.py", line 34, in _run
    await process_sync_message(message[1:], self._ydoc, self._websocket, self.log)
  File "/home/chris/.local/lib/python3.7/site-packages/ypy_websocket/yutils.py", line 120, in process_sync_message
    await websocket.send(reply)
  File "/home/chris/.local/lib/python3.7/site-packages/websockets/legacy/protocol.py", line 635, in send
    await self.ensure_open()
  File "/home/chris/.local/lib/python3.7/site-packages/websockets/legacy/protocol.py", line 953, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedOK: sent 1000 (OK); then received 1000 (OK)
```

Any pointers why this could be?

Thanks,
Chris

**Comment by davidbrochart** [comment]
Hi Chris, thanks for the kind words.
I'm not sure we had this exception in the past. Maybe `websockets` raises it in newer versions?

**Comment by cschuet** [comment]
I downgraded `websockets` to `10.1` but the exception remains on my system. If you can't reproduce, maybe the problem is with my setup.

**Comment by davidbrochart** [comment]
I can reproduce, it's actually because the client immediately finishes after sending an update, and the server echoes back this update to the client, which has already disconnected. If you add `await asyncio.sleep(0.1)` at the end of the `client` function, the exception disappears.
This is just an example showing a minimal server/client setup, but feel free to open a PR if you want to improve it.

**Comment by cschuet** [comment]
Thanks for taking the time to reproduce. Ok, haven't worked much with `asyncio` in python yet, but will send a PR if I have something. Cheers!
